version: '3.8'

services:
  rigveda-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rigveda-backend
    ports:
      - "8008:8008"
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
      - CLOUDFLARE_TUNNEL_TOKEN=eyJhIjoiOGJlNWJkYzMzYjZiNDQ0MTI3YjUwMzBlZjQyNTJlZTAiLCJ0IjoiOTI0YmJiOGMtMTE2ZC00ZjVjLWIyY2QtMmYyZTA2ZjU2NDhmIiwicyI6IllqWTJOV1ZpTlRNdE5qQTJZaTAwWTJNNUxUazBPVGd0TkRNME5UUTNPV1prWkdSaiJ9
    env_file:
      - .env
    volumes:
      # Mount essential data files (embeddings, datasets)
      - ./data/dataset:/app/data/dataset:ro
      - ./data/embeddings:/app/data/embeddings:ro
      - ./data/rig_veda_index.json:/app/data/rig_veda_index.json:ro
      # Mount cache directory for downloaded audio files
      - ./cache:/app/cache
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8008/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rigveda-network

networks:
  rigveda-network:
    driver: bridge
